marx SourceFlux=-1 SpectrumType="FILE" SpectrumFile="EQPegA_flux.tbl" \
       ExposureTime=5e5 TStart=2006.9 \
       OutputDir=EQPegA GratingType="HETG" DetectorType="ACIS-S" \
       DitherModel="INTERNAL" RA_Nom=352.966 Dec_Nom=19.935 Roll_Nom=290 \
       SourceRA=352.96851 SourceDEC=19.937133

marx SourceFlux=-1 SpectrumType="FILE" SpectrumFile="EQPegB_flux.tbl" \
       ExposureTime=5e5 TStart=2006.9 \
       OutputDir=EQPegB GratingType="HETG" DetectorType="ACIS-S" \
       DitherModel="INTERNAL" RA_Nom=352.966 Dec_Nom=19.935 Roll_Nom=290 \
       SourceRA=352.97011 SourceDEC=19.937225