# This file is included in both sh scripts and Makefiles
ISISPATH=/nfs/cxc/a1/${CSR_CARCH}/bin
ISIS=${ISISPATH}/isis
ISISSCRIPT=${ISISPATH}/isis-script
#MARXPREFIX=${HOME}/sys/${CSR_CARCH}/opt/marx5.1
MARXPREFIX=/melkor/d1/guenther/marx/installed/marx-5.4.0/

MARXFLUX=${MARXPREFIX}/lib/marx/marxflux

# CIAO setup
# CIAOSETUP=. /nfs/mkx/a1/setup/ciaox-setup.sh
CIAOSETUP=/melkor/d1/guenther/ciao/ciao-4.11/bin/ciao.sh