load_dataset ("plaw_pha.fits", "plaw_rmf.fits", "plaw_arf.fits");
rebin_data (1, 30);
xnotice_en (1, 0.3, 11);
fit_fun("phabs(1)*powerlaw(1)");
set_par(1,1,1);
fit_counts;
list_par;
plot_open("plawfit.ps/CPS");
xrange(0.3,11);
rplot_counts (1);
plot_close ();
